// <auto-generated />
using System;
using GamesAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GamesAPI.Models.Categoria", b =>
                {
                    b.Property<int>("CATEGORIA_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IMAGEM_URL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("CATEGORIA_ID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GamesAPI.Models.Jogo", b =>
                {
                    b.Property<int>("JOGO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ANO_LANCAMENTO")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("CATEGORIA_ID")
                        .HasColumnType("int");

                    b.Property<int?>("CATEGORIA_ID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATA_CADASTRO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("IMAGEM_URL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal?>("NOTA")
                        .IsRequired()
                        .HasColumnType("decimal(2,2)");

                    b.Property<decimal>("PRECO")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("JOGO_ID");

                    b.HasIndex("CATEGORIA_ID1");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("GamesAPI.Models.Jogo", b =>
                {
                    b.HasOne("GamesAPI.Models.Categoria", "Categoria")
                        .WithMany("Jogos")
                        .HasForeignKey("CATEGORIA_ID1");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GamesAPI.Models.Categoria", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
